name: CI - Terraform Validation

on:
  push:
    branches: [ main, develop, feature/* ]
  pull_request:
    branches: [ main, develop ]

env:
  TF_VERSION: "1.6.0"
  TF_VAR_slack_webhook_url: "https://hooks.slack.com/services/EXAMPLE/EXAMPLE/EXAMPLE"
  TF_VAR_budget_email: "test@example.com"

jobs:
  terraform-validate:
    name: 'Terraform Validation'
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: ${{ env.TF_VERSION }}

    - name: Terraform Format Check
      run: terraform fmt -check -recursive

    - name: Terraform Init
      run: terraform init -backend=false

    - name: Terraform Validate
      run: terraform validate

    - name: Terraform Plan (Dry Run)
      run: terraform plan -out=tfplan

  basic-tests:
    name: 'Basic Tests'
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest urllib3

    - name: Basic Python Syntax Check
      run: |
        python -m py_compile lambda_function.py
        python -m py_compile architecture.py

    - name: Check Project Structure
      run: |
        # Verify essential files exist
        test -f README.md
        test -f lambda_function.py
        test -f provider.tf
        test -f variables.tf
        test -f sns.tf
        test -f lambda.tf
        echo "✅ All essential files present"

  documentation:
    name: 'Documentation Check'
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Validate Documentation
      run: |
        # Check if all variables are documented
        grep -q "slack_webhook_url" README.md
        grep -q "budget_email" README.md
        grep -q "aws_region" README.md
        echo "✅ Documentation validation passed"